/**
 * @file EduBase_Button_Interrupt.c
 *
 * @brief Source code for the EduBase_Button_Interrupt driver.
 *
 * This file contains the function definitions for the EduBase_Button_Interrupt driver.
 * It interfaces with the EduBase Board push buttons. The following pins are used:
 *	- SW2 (PD3)
 *	- SW3 (PD2)
 *
 * It configures the pins to trigger interrupts on rising edges. The EduBase Board 
 * push buttons operate in an active high configuration.
 *
 * @author Aaron Nanas
 */

#include "EduBase_Button_Interrupt.h"

// Declare a pointer to the user-defined task
void (*EduBase_Button_Task)(uint8_t edubase_button_status);

void EduBase_Button_Interrupt_Init(void(*task)(uint8_t))
{
	// Store the user-defined task function for use during interrupt handling

	
	// Enable the clock to Port D by setting the R3 bit (Bit 3) in the RCGCGPIO register

	
	// Configure the PD3 and PD2 pins as input by clearing Bits 3 to 2 in the DIR register

	
	// Configure the PD3 and PD2 pins to function as
	// GPIO pins by clearing Bits 3 to 2 in the AFSEL register

	
	// Enable the digital functionality for the PD3 and PD2 pins
	// by setting Bits 3 to 2 in the DEN register

	
	// Enable the weak pull-down resistor for the PD3 and PD2 pins
	// by setting Bits 3 to 2 in the PDR register

	
	// Configure the PD3 and PD2 pins to detect edges
	// by clearing Bits 3 to 2 in the IS register

	
	// Allow the GPIOIEV register to handle interrupt generation
	// and determine which edge to check for the PD3 and PD2 pins 
	// by clearing Bits 3 to 2 in the IBE register

	
	// Configure the PD3 and PD2 pins to detect
	// rising edges by setting Bits 3 to 2 in the IEV register
	// Rising edges on the corresponding pins will trigger interrupts

	
	// Clear any existing interrupt flags on the PD3 and PD2 pins
	// by setting Bits 3 to 2 in the ICR register

	
	// Allow the interrupts that are generated by the PD3 and PD2 pins to be 
	// sent to the interrupt controller by setting Bits 3 to 2 in the IM register

	
	// Clear the INTD field (Bits 31 to 29) of the IPR[0] register (PRI0)

	
	// Set the priority level of the interrupts to 3. Port D has an Interrupt Request (IRQ) number of 3

	
	// Enable IRQ 3 for GPIO Port D by setting Bit 3 in the ISER[0] register

}

void GPIOD_Handler(void)
{

}
