/**
 * @file PMOD_BTN_Interrupt.h
 *
 * @brief Header file for the PMOD_BTN_Interrupt driver.
 *
 * This file contains the function definitions for the PMOD_BTN_Interrupt driver.
 * It interfaces with the PMOD BTN module. The following pins are used:
 * 	- BTN0 (PA2)
 *	- BTN1 (PA3)
 *	- BTN2 (PA4)
 *	- BTN3 (PA5)
 *
 * It configures the pins to trigger interrupts on rising edges. The PMOD BTN
 * push buttons operate in an active high configuration.
 *
 * @author Aaron Nanas
 */
 
#include "PMOD_BTN_Interrupt.h"
 
// Declare pointer to the user-defined task
void (*PMOD_BTN_Task)(uint8_t pmod_btn_state);

void PMOD_BTN_Interrupt_Init(void(*task)(uint8_t))
{
	// Store the user-defined task function for use during interrupt handling

	
	// Enable the clock to Port A by setting the
	// R0 bit (Bit 0) in the RCGCGPIO register

	
	// Configure the PA5, PA4, PA3, and PA2 pins as input
	// by clearing Bits 5 to 2 in the DIR register

	
	// Configure the PA5, PA4, PA3, and PA2 pins to function as
	// GPIO pins by clearing Bits 5 to 2 in the AFSEL register

	
	// Enable the digital functionality for the PA5, PA4, PA3, and PA2 pins
	// by setting Bits 5 to 2 in the DEN register

	
	// Enable the weak pull-down resistor for the PA5, PA4, PA3, and PA2 pins
	// by setting Bits 5 to 2 in the PDR register

	
	// Configure the PA5, PA4, PA3, and PA2 pins to detect edges
	// by clearing Bits 5 to 2 in the IS register

	
	// Allow the GPIOIEV register to handle interrupt generation
	// and determine which edge to check for the PA5, PA4, PA3, and PA2 pins 
	// by clearing Bits 5 to 2 in the IBE register

	
	// Configure the PA5, PA4, PA3, and PA2 pins to detect
	// rising edges by setting Bits 5 to 2 in the IEV register
	// Rising edges on the corresponding pins will trigger interrupts

	
	// Clear any existing interrupt flags on the PA5, PA4, PA3, and PA2 pins
	// by setting Bits 5 to 2 in the ICR register

	
	// Allow the interrupts that are generated by the PA5, PA4, PA3, and PA2 pins
	// to be sent to the interrupt controller by setting
	// Bits 5 to 2 in the IM register

	
	// Clear the INTA field (Bits 7 to 5) of the IPR[0] register (PRI0)

	
	// Set the priority level of the interrupts to 3. Port A has an Interrupt Request (IRQ) number of 0

	
	// Enable IRQ 0 for GPIO Port A by setting Bit 0 in the ISER[0] register

}

uint8_t PMOD_BTN_Read(void)
{
	return 0x00;
}

void GPIOA_Handler(void)
{

}
